# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    showuserevent:
        class: Avanzu\AdminThemeBundle\EventListener\ShowUserListener
        arguments: ['@security.token_storage']
        tags:
           - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
    sk_items:
        class: Avanzu\AdminThemeBundle\EventListener\MenuItemsListListener
        tags:
           - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }